#Spring boot server
server:
  port: 8011

### postgresql config ###
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: ll
    password: 123456
    driver-class-name: org.postgresql.Driver

